[2024-06-03T22:41:17.230-0500] {processor.py:161} INFO - Started process (PID=46345) to work on /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py
[2024-06-03T22:41:17.231-0500] {processor.py:830} INFO - Processing file /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py for tasks to queue
[2024-06-03T22:41:17.233-0500] {logging_mixin.py:188} INFO - [2024-06-03T22:41:17.233-0500] {dagbag.py:545} INFO - Filling up the DagBag from /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py
[2024-06-03T22:41:17.235-0500] {logging_mixin.py:188} INFO - [2024-06-03T22:41:17.235-0500] {dagbag.py:355} ERROR - Failed to import: /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py
Traceback (most recent call last):
  File "/home/diallo/Documents/workspace/Python/AirFlowProjects/AirFlow01/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ValueError: source code string cannot contain null bytes
[2024-06-03T22:41:17.236-0500] {processor.py:842} WARNING - No viable dags retrieved from /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py
[2024-06-03T22:41:17.256-0500] {processor.py:183} INFO - Processing /home/diallo/airflow/dags/__pycache__/data_cleaning.cpython-310.py took 0.031 seconds
